---
name: Release Go Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set env vars
        run: |
          echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build binary
        run: |
          mkdir -p dist
          for os in linux windows darwin; do
            ext=""
            if [ "${os}" = "windows" ]; then ext=".exe"; fi
            for arch in amd64 arm64; do
              GOOS=${os} GOARCH=${arch} go build -ldflags="-s -w" -o "dist/cgen-$os-$arch$ext" .
            done
          done

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
